# Generated by Django 4.1.1 on 2022-09-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sTitle', models.CharField(max_length=50)),
                ('sContent', models.TextField()),
                ('dCreated', models.DateTimeField(auto_now_add=True)),
                ('dUpdated', models.DateTimeField(auto_now_add=True)),
                ('iImage', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
