# Generated by Django 4.1.1 on 2022-09-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sTitle', models.CharField(max_length=50, verbose_name='제목')),
                ('sContent', models.TextField(verbose_name='내용')),
                ('dCreated', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('dUpdated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('iImage', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='이미지')),
            ],
            options={
                'verbose_name': '게시판 내용',
                'verbose_name_plural': '게시판 내용',
                'db_table': 'board_content',
            },
        ),
    ]
