# Generated by Django 4.1.1 on 2022-09-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board_content',
            options={'verbose_name': '게시판 내용', 'verbose_name_plural': '게시판 내용'},
        ),
        migrations.AlterField(
            model_name='board_content',
            name='dCreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='board_content',
            name='dUpdated',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='board_content',
            name='iImage',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='board_content',
            name='sContent',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='board_content',
            name='sTitle',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
        migrations.AlterModelTable(
            name='board_content',
            table='board_content',
        ),
    ]
